USE [master]
GO

/****** Object:  Database [ITM]    Script Date: 13/03/2025 11:14:54 a. m. ******/
CREATE DATABASE [ITM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ITM', FILENAME = N'C:\SQLData\Data\ITM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ITM_log', FILENAME = N'C:\SQLData\Data\ITM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ITM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ITM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ITM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ITM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ITM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ITM] SET ARITHABORT OFF 
GO

ALTER DATABASE [ITM] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ITM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ITM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ITM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ITM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ITM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ITM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ITM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ITM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ITM] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ITM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ITM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ITM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ITM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ITM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ITM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ITM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ITM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ITM] SET  MULTI_USER 
GO

ALTER DATABASE [ITM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ITM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ITM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ITM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ITM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ITM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ITM] SET QUERY_STORE = ON
GO

ALTER DATABASE [ITM] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ITM] SET  READ_WRITE 
GO

