//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARCIAL1APPSERVICIOS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Computador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computador()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int id_computador { get; set; }
        public int id_tipo { get; set; }
        public Nullable<int> num_procesadores { get; set; }
        public string marca_procesador { get; set; }
        public string tamano_disco { get; set; }
        public string tamano_memoria { get; set; }
        public string componentes { get; set; }

        [JsonIgnore]
        public virtual Tipo_Computador Tipo_Computador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        [JsonIgnore]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
